[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ev_charging = "CbhmEH9wJTGShWpyHebvj15DXFJu7TkMK7pXydc9qoQ1"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
 test = "mocha --require ts-node/register --timeout 1000000 --recursive tests/**/*.ts"
