[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ev_charging = "5FyPMX3L9MZCgfBmrC42RmKv6qzs91e8KFtF2MHTJqbZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
 test = "mocha --require ts-node/register --timeout 1000000 --recursive tests/**/*.ts"
